# Generated by Django 4.2.30 on 2026-07-14 11:15

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistica', '0002_formulariodinamico_foto_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariodinamico',
            name='client_submission_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EventoRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregunta_key', models.CharField(max_length=100)),
                ('pregunta_descripcion', models.CharField(max_length=255)),
                ('valor', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField()),
                ('geoposicion', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('foto_url', models.TextField(blank=True, null=True)),
                ('foto_local', models.TextField(blank=True, null=True)),
                ('entidad_nombre', models.CharField(max_length=255)),
                ('ultimo_chequeo', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_respuesta', to='logistica.pdv')),
                ('replenisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_respuesta', to=settings.AUTH_USER_MODEL)),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_respuesta', to='logistica.routestop')),
            ],
            options={
                'db_table': 'logistica_evento_respuesta',
                'ordering': ['answered_at'],
                'indexes': [models.Index(fields=['route_stop', 'pregunta_key'], name='logistica_e_route_s_b8e899_idx'), models.Index(fields=['answered_at'], name='logistica_e_answere_53a9fc_idx')],
            },
        ),
    ]
